



Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-066784287e358dad1
      InstanceType: t2.micro
      KeyName: testKeypair  # Replace with your actual key pair name
      SecurityGroups:
        - !Ref SSHSecurityGroup

  # our EC2 security group for ssh
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22


#~/.ssh/authorized_keys

# Format: IP address/prefix length
# Example: 192.168.1.0/24
# 192.168.1.0 -> 11000000.10101000.00000001.00000000 

# /32: Single IP (e.g., 192.168.1.5/32)
# /24: 256 IPs in a network (e.g., 192.168.1.0/24) ,192.168.1.0 ,192.168.1.1,192.168.1.2 , 192.168.1.3 ... 255
# /16: 65,536 IPs in a network (e.g., 192.168.0.0/16)
# /8: 16,777,216 IPs in a network (e.g., 10.0.0.0/8)
